# Generated by Django 5.2.11 on 2026-02-12 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanjaya_reports_created', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanjaya_reports_published', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanjaya_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'permissions': [('can_view_any', 'Can view any report'), ('can_edit_any', 'Can edit any report'), ('can_publish_any', 'Can publish any report'), ('can_destroy_any', 'Can destroy any report'), ('can_manage_shares_any', 'Can manage shares on any report'), ('can_transfer_ownership_any', 'Can transfer ownership of any report')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DynamicReportGroupShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanjaya_shared_reports', to='auth.group')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_shares', to='sanjaya_ninja.dynamicreport')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('report', 'group')},
            },
        ),
        migrations.CreateModel(
            name='DynamicReportUserShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shares', to='sanjaya_ninja.dynamicreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanjaya_shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('report', 'user')},
            },
        ),
    ]
